#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include "Point.hpp"
#include "Forme.hpp"
#include "Rectangle.hpp"
#include "Draw.hpp"
#include "Carre.hpp"
#include "Menu.hpp"
#include "MenuOutils.hpp"
//#include "Formes.hpp"
//#include "Cercle.hpp"
