#!/bin/bash
g++ -c main.cpp
g++ -c Point.cpp
g++ -c Forme.cpp
g++ -c Rectangle.cpp
g++ -c Draw.cpp
g++ -c Carre.cpp
#g++ -c Cercle.cpp
g++ -c include.cpp
g++ -c Menu.cpp
#g++ -c Formes.cpp
g++ -c MenuOutils.cpp
g++ -c main.cpp -I/include
g++ main.o Menu.o MenuOutils.o  include.o Carre.o Draw.o Forme.o Rectangle.o Point.o -o sfml-app -lsfml-graphics -lsfml-window -lsfml-system
